import { useState } from 'react';
import './App.css';
import { UploadArea } from './components/UploadArea';
import { NetlistViewer } from './components/NetlistViewer';
import { ComponentList } from './components/ComponentList';
import type { CircuitComponent } from './types';

function App() {
  const [file, setFile] = useState<File | null>(null);

  const handleFileSelect = (selectedFile: File) => {
    console.log("File selected:", selectedFile.name);
    setFile(selectedFile);
  };

  // Dummy Data for Preview
  const [netlist, setNetlist] = useState<string>(`* SPICE Netlist Generated by Toaster
                                                    V1 N0001 0 5V
                                                    R1 N0001 N0002 10k
                                                    LED1 N0002 0 Red
                                                    .backanno
                                                    .end`);

  const [components, setComponents] = useState<CircuitComponent[]>([
    { id: 1, type: 'Resistor', name: 'R1', terminals: ['A1', 'A5'], value: '10k' },
    { id: 2, type: 'LED', name: 'LED1', terminals: ['A5', 'Ground'], value: 'Red' },
    { id: 3, type: 'Source', name: 'V1', terminals: ['A1', 'Ground'], value: '5V' },
  ]);

  const handleComponentUpdate = (id: number, field: keyof CircuitComponent, value: string) => {
    setComponents((prev) =>
      prev.map((comp) => (comp.id === id ? { ...comp, [field]: value } : comp))
    );
  };

  return (
    <div className="app-container">
      <header className="app-header">
        <h1 className="app-title">Toaster</h1>
        <p>Breadboard to SPICE Netlist Converter</p>
      </header>

      <div className="main-layout">

        {/* Left Column: Input */}
        <div className="column">
          <div>
            <h2 className="section-title">Input Image</h2>
            <UploadArea onFileSelect={handleFileSelect} />
            {file && (
              <div className="file-name">
                Selected: <strong>{file.name}</strong>
              </div>
            )}
          </div>
        </div>

        {/* Right Column: Results */}
        <div className="column">

          <div>
            <h2 className="section-title">Detected Components</h2>
            <ComponentList components={components} onUpdate={handleComponentUpdate} />
          </div>

          <div>
            <h2 className="section-title">SPICE Output</h2>
            <NetlistViewer netlist={netlist} onNetlistChange={setNetlist} />
          </div>

        </div>

      </div>
    </div>
  );
}

export default App;
